image: golang:1.4

before_script:
- source ci/prepare

Bleeding Edge:
  script:
  - source ci/build
  - '[[ -n "$AWS_SECRET_ACCESS_KEY" ]] && make s3-upload "S3_UPLOAD_PATH=$CI_BUILD_REF_NAME"'
  only:
  - branches

Stable Release:
  script:
  - export RELEASE=true
  - source ci/build
  - '[[ -n "$AWS_SECRET_ACCESS_KEY" ]] && make s3-upload "S3_UPLOAD_PATH=$CI_BUILD_REF_NAME"'
  - '[[ -n "$AWS_SECRET_ACCESS_KEY" ]] && make s3-upload "S3_UPLOAD_PATH=latest"'
  - '[[ -n "$PACKAGECLOUD_TOKEN" ]] && make packagecloud'
  only:
  - tags
