image: golang:1.6

stages:
- prebuild
- test
- build
- package
- deploy

before_script:
- source ci/prepare

.docker: &docker
  before_script:
  - source ci/prepare
  - wget -O /usr/bin/docker https://get.docker.com/builds/Linux/x86_64/docker-1.10.3
  - chmod +x /usr/bin/docker
  services: ["docker:dind"]
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://docker:2375

bindata:
  <<: *docker
  stage: prebuild
  script:
  - apt-get install -yqqq xz-utils
  - make deps
  - make docker
  artifacts:
    paths:
    - out/docker/prebuilt-x86_64.tar.xz
    - out/docker/prebuilt-arm.tar.xz
    - executors/docker/bindata.go
    expire_in: 7d

code style:
  stage: test
  script:
  - make deps
  - make fmt
  - make lint 
  - make complexity

unit tests:
  stage: test
  script:
  - make deps
  - make test

docker executor:
  <<: *docker
  stage: test
  script:
  - go test -cover ./executor/docker/

binaries:
  stage: build
  script:
  - make build
  artifacts:
    paths:
    - out/binaries/
    expire_in: 7d

packages:
  stage: package
  script:
  - apt-get install -yqqq ruby ruby-dev python-pip dpkg-sig createrepo rpm
  - make package
  artifacts:
    paths:
    - out/deb/
    - out/rpm/
    expire_in: 7d

development:
  stage: deploy
  script:
  - make s3-upload "S3_UPLOAD_PATH=$CI_BUILD_REF_NAME"
  only:
  - branches@gitlab-org/gitlab-ci-multi-runner
  except:
  - master@gitlab-org/gitlab-ci-multi-runner
  tags:
  - deploy
  environment: bleeding_edge

bleeding:
  stage: deploy
  script:
  - apt-get install -yqqq ruby-dev
  - make s3-upload "S3_UPLOAD_PATH=$CI_BUILD_REF_NAME"
  - make packagecloud "PACKAGE_CLOUD=runner/unstable" DEB_PLATFORMS="debian/jessie ubuntu/trusty" RPM_PLATFORMS="el/7 fedora/23"
  only:
  - master@gitlab-org/gitlab-ci-multi-runner
  tags:
  - deploy
  environment: bleeding_edge

stable:
  stage: deploy
  script:
  - make s3-upload "S3_UPLOAD_PATH=$CI_BUILD_REF_NAME"
  - make s3-upload "S3_UPLOAD_PATH=latest"
  - apt-get install -yqqq ruby-dev
  - make packagecloud
  only:
  - tags@gitlab-org/gitlab-ci-multi-runner
  tags:
  - deploy
  environment: stable_release
