language: go
sudo: false
addons:
  apt:
    packages:
    - rpm
go:
- '1.4'
env:
  global:
    secure: COMQYKj9O6GUuoDRa5OVfOT8i4m1f/JDH6LaGLI8Nkb84oaq9fgvpjVMBgUcWbYT52UXt3NNy7N8B3d8VEmCHvBIjZh296OhHsAvFf9hvcjx5POjKXODV1rwdgtyYafaLUPllCBe/lLKn819ktD3PB1tjxQ0//r4APW82W4wpYs=
install:
- make deps
script:
- make lint
- make test
before_deploy:
- make toolchain
- make build
- make package
- '[[ -z "$TRAVIS_TAG" ]] || make packagecloud'
deploy:
- provider: releases
  api_key:
    secure: WBb1z0GV1uD8pB/UMDVqiqIFHcgxl2fngF9Qg8Obe0IJIuBN8ak4H1ulYKYcRgguJjefMG/OnPT2xHCsSme+OanxBcGDiYijG1vVmBqnMV8wTK5ulqkgSz7QVH4oCmdqd8WnHKqqqXmLUARRAUkvKFDCf2mq6qyAy+wKw7jPluI=
  file:
    - out/binaries/gitlab-ci-multi-runner-linux-arm
    - out/binaries/gitlab-ci-multi-runner-linux-386
    - out/binaries/gitlab-ci-multi-runner-linux-amd64
    - out/binaries/gitlab-ci-multi-runner-darwin-386
    - out/binaries/gitlab-ci-multi-runner-darwin-amd64
    - out/binaries/gitlab-ci-multi-runner-windows-386.exe
    - out/binaries/gitlab-ci-multi-runner-windows-amd64.exe
  on:
    repo: ayufan/gitlab-ci-multi-runner
    tags: true
- provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: repo.ayufan.eu
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  local_dir: out/
  upload_dir: gitlab-ci-multi-runner/master
  on:
    repo: ayufan/gitlab-ci-multi-runner
    branch: master
- provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: repo.ayufan.eu
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  local_dir: out/
  upload_dir: gitlab-ci-multi-runner/$TRAVIS_TAG
  on:
    repo: ayufan/gitlab-ci-multi-runner
    tags: true
- provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: repo.ayufan.eu
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  local_dir: out/
  upload_dir: gitlab-ci-multi-runner/latest
  on:
    repo: ayufan/gitlab-ci-multi-runner
    tags: true
